CREATE TABLE IF NOT EXISTS admin_state_snapshot (
  snapshot_key VARCHAR(64) PRIMARY KEY,
  snapshot_json LONGTEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

