-- 积分商城 D03~D07 初始化建表脚本（从 mysql设计.md 抽取）
-- 生成时间: 2026-03-17
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pm_dict_type;
DROP TABLE IF EXISTS pm_dict_item;
DROP TABLE IF EXISTS pm_system_config;
DROP TABLE IF EXISTS pm_user;
DROP TABLE IF EXISTS pm_user_auth;
DROP TABLE IF EXISTS pm_user_address;
DROP TABLE IF EXISTS pm_point_account;
DROP TABLE IF EXISTS pm_point_ledger;
DROP TABLE IF EXISTS pm_point_rule;
DROP TABLE IF EXISTS pm_category;
DROP TABLE IF EXISTS pm_product_spu;
DROP TABLE IF EXISTS pm_product_sku;
DROP TABLE IF EXISTS pm_product_media;
DROP TABLE IF EXISTS pm_product_attr_def;
DROP TABLE IF EXISTS pm_product_attr_value;
DROP TABLE IF EXISTS pm_recommend_slot;
DROP TABLE IF EXISTS pm_recommend_item;
DROP TABLE IF EXISTS pm_group_resource;
DROP TABLE IF EXISTS pm_exchange_order;
DROP TABLE IF EXISTS pm_exchange_order_item;
DROP TABLE IF EXISTS pm_order_address_snapshot;
DROP TABLE IF EXISTS pm_order_delivery;
DROP TABLE IF EXISTS pm_order_flow;
DROP TABLE IF EXISTS pm_backpack_asset;
DROP TABLE IF EXISTS pm_backpack_asset_flow;
DROP TABLE IF EXISTS pm_idempotent_request;

CREATE TABLE pm_dict_type (
  id                BIGINT UNSIGNED PRIMARY KEY,
  tenant_id         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  dict_type_code    VARCHAR(64) NOT NULL,
  dict_type_name    VARCHAR(128) NOT NULL,
  status_code       VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json          JSON NULL,
  remark            VARCHAR(500) NULL,
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted        TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at        DATETIME(3) NULL,
  UNIQUE KEY uk_type_tenant_code (tenant_id, dict_type_code),
  KEY idx_type_status (status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型';

CREATE TABLE pm_dict_item (
  id                BIGINT UNSIGNED PRIMARY KEY,
  tenant_id         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  dict_type_code    VARCHAR(64) NOT NULL,
  item_code         VARCHAR(64) NOT NULL,
  item_name         VARCHAR(128) NOT NULL,
  item_value        VARCHAR(255) NULL,
  sort_no           INT NOT NULL DEFAULT 0,
  status_code       VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  color_code        VARCHAR(32) NULL,
  ext_json          JSON NULL,
  remark            VARCHAR(500) NULL,
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted        TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at        DATETIME(3) NULL,
  UNIQUE KEY uk_item_tenant_type_code (tenant_id, dict_type_code, item_code),
  KEY idx_item_type_sort (dict_type_code, sort_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典明细';

CREATE TABLE pm_system_config (
  id                BIGINT UNSIGNED PRIMARY KEY,
  tenant_id         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  config_key        VARCHAR(128) NOT NULL,
  config_name       VARCHAR(128) NOT NULL,
  config_value      TEXT NULL,
  value_type_code   VARCHAR(32) NOT NULL DEFAULT 'STRING',
  group_code        VARCHAR(64) NOT NULL DEFAULT 'DEFAULT',
  status_code       VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json          JSON NULL,
  remark            VARCHAR(500) NULL,
  created_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by        BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted        TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at        DATETIME(3) NULL,
  UNIQUE KEY uk_cfg_tenant_key (tenant_id, config_key),
  KEY idx_cfg_group (group_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统配置';

CREATE TABLE pm_user (
  id                    BIGINT UNSIGNED PRIMARY KEY,
  tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  app_id                VARCHAR(64) NOT NULL DEFAULT 'wxapp',
  user_no               VARCHAR(32) NOT NULL,
  union_id              VARCHAR(128) NULL,
  open_id               VARCHAR(128) NULL,
  phone                 VARCHAR(20) NULL,
  phone_masked          VARCHAR(20) NULL,
  nick_name             VARCHAR(128) NULL,
  avatar_url            VARCHAR(512) NULL,
  gender_code           VARCHAR(32) NULL,
  register_channel_code VARCHAR(64) NOT NULL DEFAULT 'WXAPP',
  status_code           VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  register_at           DATETIME(3) NULL,
  last_login_at         DATETIME(3) NULL,
  last_login_ip         VARCHAR(64) NULL,
  ext_json              JSON NULL,
  version               INT UNSIGNED NOT NULL DEFAULT 0,
  remark                VARCHAR(500) NULL,
  created_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted            TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at            DATETIME(3) NULL,
  UNIQUE KEY uk_user_tenant_user_no (tenant_id, user_no),
  UNIQUE KEY uk_user_tenant_open_id (tenant_id, open_id),
  KEY idx_user_phone (phone),
  KEY idx_user_status (status_code),
  KEY idx_user_register_at (register_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户主表';

CREATE TABLE pm_user_auth (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id            BIGINT UNSIGNED NOT NULL,
  auth_type_code     VARCHAR(32) NOT NULL,
  auth_identifier    VARCHAR(256) NOT NULL,
  auth_credential    VARCHAR(512) NULL,
  credential_salt    VARCHAR(128) NULL,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  verified_at        DATETIME(3) NULL,
  ext_json           JSON NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_auth_tenant_type_identifier (tenant_id, auth_type_code, auth_identifier),
  KEY idx_auth_user (user_id),
  KEY idx_auth_status (status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户认证信息';

CREATE TABLE pm_user_address (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id            BIGINT UNSIGNED NOT NULL,
  receiver_name      VARCHAR(64) NOT NULL,
  receiver_phone     VARCHAR(20) NOT NULL,
  country_code       VARCHAR(16) NOT NULL DEFAULT 'CN',
  province_code      VARCHAR(32) NULL,
  province_name      VARCHAR(64) NOT NULL,
  city_code          VARCHAR(32) NULL,
  city_name          VARCHAR(64) NOT NULL,
  district_code      VARCHAR(32) NULL,
  district_name      VARCHAR(64) NOT NULL,
  street_name        VARCHAR(128) NULL,
  detail_address     VARCHAR(255) NOT NULL,
  postal_code        VARCHAR(16) NULL,
  is_default         TINYINT(1) NOT NULL DEFAULT 0,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  ext_json           JSON NULL,
  remark             VARCHAR(500) NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  KEY idx_addr_user (user_id),
  KEY idx_addr_user_default (user_id, is_default),
  KEY idx_addr_status (status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户收货地址';

CREATE TABLE pm_point_account (
  id                    BIGINT UNSIGNED PRIMARY KEY,
  tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id               BIGINT UNSIGNED NOT NULL,
  point_balance         BIGINT NOT NULL DEFAULT 0,
  point_frozen          BIGINT NOT NULL DEFAULT 0,
  point_total_income    BIGINT NOT NULL DEFAULT 0,
  point_total_expense   BIGINT NOT NULL DEFAULT 0,
  account_status_code   VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  last_change_at        DATETIME(3) NULL,
  ext_json              JSON NULL,
  version               INT UNSIGNED NOT NULL DEFAULT 0,
  remark                VARCHAR(500) NULL,
  created_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted            TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at            DATETIME(3) NULL,
  UNIQUE KEY uk_point_account_user (tenant_id, user_id),
  KEY idx_point_account_status (account_status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分账户';

CREATE TABLE pm_point_ledger (
  id                    BIGINT UNSIGNED PRIMARY KEY,
  tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ledger_no             VARCHAR(32) NOT NULL,
  user_id               BIGINT UNSIGNED NOT NULL,
  account_id            BIGINT UNSIGNED NOT NULL,
  change_type_code      VARCHAR(32) NOT NULL,
  business_type_code    VARCHAR(32) NOT NULL,
  source_type_code      VARCHAR(32) NOT NULL,
  source_no             VARCHAR(64) NULL,
  direction_code        VARCHAR(16) NOT NULL,
  change_amount         BIGINT NOT NULL,
  before_balance        BIGINT NOT NULL,
  after_balance         BIGINT NOT NULL,
  frozen_change_amount  BIGINT NOT NULL DEFAULT 0,
  before_frozen         BIGINT NOT NULL DEFAULT 0,
  after_frozen          BIGINT NOT NULL DEFAULT 0,
  occurred_at           DATETIME(3) NOT NULL,
  channel_code          VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
  operator_type_code    VARCHAR(32) NOT NULL DEFAULT 'SYSTEM',
  operator_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  idempotent_no         VARCHAR(64) NULL,
  ext_json              JSON NULL,
  remark                VARCHAR(500) NULL,
  created_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted            TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at            DATETIME(3) NULL,
  UNIQUE KEY uk_ledger_no (ledger_no),
  UNIQUE KEY uk_ledger_idempotent (tenant_id, idempotent_no),
  KEY idx_ledger_user_time (user_id, occurred_at),
  KEY idx_ledger_source (source_type_code, source_no),
  KEY idx_ledger_business_type (business_type_code),
  KEY idx_ledger_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分流水';

CREATE TABLE pm_point_rule (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rule_code          VARCHAR(64) NOT NULL,
  rule_name          VARCHAR(128) NOT NULL,
  scene_code         VARCHAR(64) NOT NULL,
  change_type_code   VARCHAR(32) NOT NULL,
  calc_type_code     VARCHAR(32) NOT NULL DEFAULT 'FIXED',
  fixed_amount       BIGINT NULL,
  calc_expression    VARCHAR(1000) NULL,
  priority_no        INT NOT NULL DEFAULT 100,
  valid_start_at     DATETIME(3) NULL,
  valid_end_at       DATETIME(3) NULL,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json           JSON NULL,
  remark             VARCHAR(500) NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_rule_tenant_code (tenant_id, rule_code),
  KEY idx_rule_scene_status (scene_code, status_code),
  KEY idx_rule_valid_time (valid_start_at, valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分规则';

CREATE TABLE pm_category (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  category_no        VARCHAR(32) NOT NULL,
  parent_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  level_no           INT NOT NULL DEFAULT 1,
  category_name      VARCHAR(128) NOT NULL,
  category_icon      VARCHAR(512) NULL,
  sort_no            INT NOT NULL DEFAULT 0,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  leaf_flag          TINYINT(1) NOT NULL DEFAULT 1,
  ext_json           JSON NULL,
  remark             VARCHAR(500) NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_category_no (tenant_id, category_no),
  KEY idx_category_parent (parent_id),
  KEY idx_category_status_sort (status_code, sort_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品分类';

CREATE TABLE pm_product_spu (
  id                       BIGINT UNSIGNED PRIMARY KEY,
  tenant_id                BIGINT UNSIGNED NOT NULL DEFAULT 0,
  product_no               VARCHAR(32) NOT NULL,
  product_name             VARCHAR(256) NOT NULL,
  sub_title                VARCHAR(256) NULL,
  product_type_code        VARCHAR(32) NOT NULL,
  category_id              BIGINT UNSIGNED NOT NULL,
  brand_name               VARCHAR(128) NULL,
  unit_name                VARCHAR(32) NOT NULL DEFAULT '件',
  main_image_url           VARCHAR(512) NULL,
  detail_content           LONGTEXT NULL,
  exchange_notice          VARCHAR(1000) NULL,
  point_price              BIGINT NOT NULL,
  market_price_amount      DECIMAL(12,2) NULL,
  stock_total              INT NOT NULL DEFAULT 0,
  stock_available          INT NOT NULL DEFAULT 0,
  stock_locked             INT NOT NULL DEFAULT 0,
  sale_status_code         VARCHAR(32) NOT NULL DEFAULT 'OFF_SHELF',
  review_status_code       VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
  recommend_flag           TINYINT(1) NOT NULL DEFAULT 0,
  hot_flag                 TINYINT(1) NOT NULL DEFAULT 0,
  new_flag                 TINYINT(1) NOT NULL DEFAULT 0,
  sort_no                  INT NOT NULL DEFAULT 0,
  limit_per_user           INT NOT NULL DEFAULT 0,
  valid_start_at           DATETIME(3) NULL,
  valid_end_at             DATETIME(3) NULL,
  biz_ref_type_code        VARCHAR(32) NULL,
  biz_ref_id               BIGINT UNSIGNED NULL,
  ext_json                 JSON NULL,
  version                  INT UNSIGNED NOT NULL DEFAULT 0,
  remark                   VARCHAR(500) NULL,
  created_by               BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at               DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by               BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at               DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted               TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at               DATETIME(3) NULL,
  UNIQUE KEY uk_spu_no (tenant_id, product_no),
  KEY idx_spu_category (category_id),
  KEY idx_spu_sale_status (sale_status_code),
  KEY idx_spu_type_status (product_type_code, sale_status_code),
  KEY idx_spu_recommend (recommend_flag, sort_no, created_at),
  KEY idx_spu_valid_time (valid_start_at, valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SPU';

CREATE TABLE pm_product_sku (
  id                    BIGINT UNSIGNED PRIMARY KEY,
  tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  spu_id                BIGINT UNSIGNED NOT NULL,
  sku_no                VARCHAR(32) NOT NULL,
  sku_name              VARCHAR(256) NOT NULL,
  spec_json             JSON NULL,
  point_price           BIGINT NOT NULL,
  stock_total           INT NOT NULL DEFAULT 0,
  stock_available       INT NOT NULL DEFAULT 0,
  stock_locked          INT NOT NULL DEFAULT 0,
  sale_status_code      VARCHAR(32) NOT NULL DEFAULT 'OFF_SHELF',
  weight_gram           INT NULL,
  volume_cm3            INT NULL,
  ext_json              JSON NULL,
  version               INT UNSIGNED NOT NULL DEFAULT 0,
  remark                VARCHAR(500) NULL,
  created_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted            TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at            DATETIME(3) NULL,
  UNIQUE KEY uk_sku_no (tenant_id, sku_no),
  KEY idx_sku_spu (spu_id),
  KEY idx_sku_status (sale_status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SKU（V1 可一SPU一SKU）';

CREATE TABLE pm_product_media (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  spu_id             BIGINT UNSIGNED NOT NULL,
  sku_id             BIGINT UNSIGNED NULL,
  media_type_code    VARCHAR(32) NOT NULL,
  media_url          VARCHAR(512) NOT NULL,
  media_name         VARCHAR(128) NULL,
  sort_no            INT NOT NULL DEFAULT 0,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json           JSON NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  KEY idx_media_spu (spu_id),
  KEY idx_media_sku (sku_id),
  KEY idx_media_type_status (media_type_code, status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品媒体资源';

CREATE TABLE pm_product_attr_def (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  attr_code          VARCHAR(64) NOT NULL,
  attr_name          VARCHAR(128) NOT NULL,
  data_type_code     VARCHAR(32) NOT NULL,
  unit_name          VARCHAR(32) NULL,
  required_flag      TINYINT(1) NOT NULL DEFAULT 0,
  scope_code         VARCHAR(32) NOT NULL DEFAULT 'SPU',
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json           JSON NULL,
  remark             VARCHAR(500) NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_attr_code (tenant_id, attr_code),
  KEY idx_attr_scope_status (scope_code, status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品属性定义';

CREATE TABLE pm_product_attr_value (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  spu_id             BIGINT UNSIGNED NULL,
  sku_id             BIGINT UNSIGNED NULL,
  attr_code          VARCHAR(64) NOT NULL,
  attr_value         VARCHAR(1000) NULL,
  attr_value_json    JSON NULL,
  sort_no            INT NOT NULL DEFAULT 0,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json           JSON NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  KEY idx_attr_value_spu (spu_id),
  KEY idx_attr_value_sku (sku_id),
  KEY idx_attr_value_code (attr_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品属性值';

CREATE TABLE pm_recommend_slot (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  slot_code          VARCHAR(64) NOT NULL,
  slot_name          VARCHAR(128) NOT NULL,
  page_code          VARCHAR(64) NOT NULL,
  scene_code         VARCHAR(64) NULL,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  sort_no            INT NOT NULL DEFAULT 0,
  ext_json           JSON NULL,
  remark             VARCHAR(500) NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_slot_code (tenant_id, slot_code),
  KEY idx_slot_page_status (page_code, status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='推荐位';

CREATE TABLE pm_recommend_item (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  slot_id            BIGINT UNSIGNED NOT NULL,
  target_type_code   VARCHAR(32) NOT NULL,
  target_id          BIGINT UNSIGNED NOT NULL,
  title              VARCHAR(256) NULL,
  sub_title          VARCHAR(256) NULL,
  image_url          VARCHAR(512) NULL,
  sort_no            INT NOT NULL DEFAULT 0,
  valid_start_at     DATETIME(3) NULL,
  valid_end_at       DATETIME(3) NULL,
  status_code        VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json           JSON NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  KEY idx_reco_slot_sort (slot_id, sort_no),
  KEY idx_reco_target (target_type_code, target_id),
  KEY idx_reco_valid_time (valid_start_at, valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='推荐位内容';

CREATE TABLE pm_group_resource (
  id                  BIGINT UNSIGNED PRIMARY KEY,
  tenant_id           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  resource_no         VARCHAR(32) NOT NULL,
  group_name          VARCHAR(128) NOT NULL,
  qr_image_url        VARCHAR(512) NOT NULL,
  intro_text          VARCHAR(1000) NULL,
  max_member_count    INT NULL,
  current_member_count INT NULL,
  expire_at           DATETIME(3) NULL,
  status_code         VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  ext_json            JSON NULL,
  remark              VARCHAR(500) NULL,
  created_by          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted          TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at          DATETIME(3) NULL,
  UNIQUE KEY uk_group_resource_no (tenant_id, resource_no),
  KEY idx_group_status (status_code),
  KEY idx_group_expire_at (expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='群聊二维码资源';

CREATE TABLE pm_exchange_order (
  id                     BIGINT UNSIGNED PRIMARY KEY,
  tenant_id              BIGINT UNSIGNED NOT NULL DEFAULT 0,
  app_id                 VARCHAR(64) NOT NULL DEFAULT 'wxapp',
  order_no               VARCHAR(32) NOT NULL,
  user_id                BIGINT UNSIGNED NOT NULL,
  order_type_code        VARCHAR(32) NOT NULL DEFAULT 'EXCHANGE',
  product_type_code      VARCHAR(32) NOT NULL,
  order_status_code      VARCHAR(32) NOT NULL,
  pay_status_code        VARCHAR(32) NOT NULL DEFAULT 'NOT_APPLICABLE',
  delivery_status_code   VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  total_point_amount     BIGINT NOT NULL,
  total_item_count       INT NOT NULL DEFAULT 1,
  user_remark            VARCHAR(500) NULL,
  admin_remark           VARCHAR(500) NULL,
  reject_reason          VARCHAR(500) NULL,
  source_channel_code    VARCHAR(64) NOT NULL DEFAULT 'WXAPP',
  source_scene_code      VARCHAR(64) NULL,
  idempotent_no          VARCHAR(64) NULL,
  request_no             VARCHAR(64) NULL,
  submit_at              DATETIME(3) NOT NULL,
  audit_at               DATETIME(3) NULL,
  ship_at                DATETIME(3) NULL,
  finish_at              DATETIME(3) NULL,
  cancel_at              DATETIME(3) NULL,
  ext_json               JSON NULL,
  version                INT UNSIGNED NOT NULL DEFAULT 0,
  created_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted             TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at             DATETIME(3) NULL,
  UNIQUE KEY uk_order_no (tenant_id, order_no),
  UNIQUE KEY uk_order_idempotent (tenant_id, idempotent_no),
  KEY idx_order_user_time (user_id, created_at),
  KEY idx_order_status_time (order_status_code, created_at),
  KEY idx_order_product_type (product_type_code),
  KEY idx_order_submit_at (submit_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='兑换订单主表';

CREATE TABLE pm_exchange_order_item (
  id                     BIGINT UNSIGNED PRIMARY KEY,
  tenant_id              BIGINT UNSIGNED NOT NULL DEFAULT 0,
  order_id               BIGINT UNSIGNED NOT NULL,
  order_no               VARCHAR(32) NOT NULL,
  user_id                BIGINT UNSIGNED NOT NULL,
  spu_id                 BIGINT UNSIGNED NOT NULL,
  sku_id                 BIGINT UNSIGNED NULL,
  product_no             VARCHAR(32) NOT NULL,
  product_name_snapshot  VARCHAR(256) NOT NULL,
  product_type_code      VARCHAR(32) NOT NULL,
  main_image_snapshot    VARCHAR(512) NULL,
  spec_snapshot_json     JSON NULL,
  unit_point_price       BIGINT NOT NULL,
  quantity               INT NOT NULL DEFAULT 1,
  total_point_amount     BIGINT NOT NULL,
  biz_ref_type_code      VARCHAR(32) NULL,
  biz_ref_id             BIGINT UNSIGNED NULL,
  ext_json               JSON NULL,
  created_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted             TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at             DATETIME(3) NULL,
  KEY idx_order_item_order (order_id),
  KEY idx_order_item_order_no (order_no),
  KEY idx_order_item_user (user_id),
  KEY idx_order_item_spu_sku (spu_id, sku_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='兑换订单明细';

CREATE TABLE pm_order_address_snapshot (
  id                 BIGINT UNSIGNED PRIMARY KEY,
  tenant_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  order_id           BIGINT UNSIGNED NOT NULL,
  order_no           VARCHAR(32) NOT NULL,
  user_id            BIGINT UNSIGNED NOT NULL,
  receiver_name      VARCHAR(64) NOT NULL,
  receiver_phone     VARCHAR(20) NOT NULL,
  country_code       VARCHAR(16) NOT NULL DEFAULT 'CN',
  province_name      VARCHAR(64) NOT NULL,
  city_name          VARCHAR(64) NOT NULL,
  district_name      VARCHAR(64) NOT NULL,
  street_name        VARCHAR(128) NULL,
  detail_address     VARCHAR(255) NOT NULL,
  postal_code        VARCHAR(16) NULL,
  ext_json           JSON NULL,
  created_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted         TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at         DATETIME(3) NULL,
  UNIQUE KEY uk_order_addr_order (tenant_id, order_id),
  KEY idx_order_addr_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单地址快照';

CREATE TABLE pm_order_delivery (
  id                   BIGINT UNSIGNED PRIMARY KEY,
  tenant_id            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  order_id             BIGINT UNSIGNED NOT NULL,
  order_no             VARCHAR(32) NOT NULL,
  delivery_type_code   VARCHAR(32) NOT NULL DEFAULT 'EXPRESS',
  logistics_company    VARCHAR(128) NULL,
  logistics_code       VARCHAR(64) NULL,
  logistics_no         VARCHAR(128) NULL,
  shipper_phone        VARCHAR(20) NULL,
  shipped_at           DATETIME(3) NULL,
  signed_at            DATETIME(3) NULL,
  delivery_status_code VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  ext_json             JSON NULL,
  remark               VARCHAR(500) NULL,
  created_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted           TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at           DATETIME(3) NULL,
  UNIQUE KEY uk_delivery_order (tenant_id, order_id),
  KEY idx_delivery_order_no (order_no),
  KEY idx_delivery_logistics_no (logistics_no),
  KEY idx_delivery_status (delivery_status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单物流';

CREATE TABLE pm_order_flow (
  id                   BIGINT UNSIGNED PRIMARY KEY,
  tenant_id            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  order_id             BIGINT UNSIGNED NOT NULL,
  order_no             VARCHAR(32) NOT NULL,
  from_status_code     VARCHAR(32) NULL,
  to_status_code       VARCHAR(32) NOT NULL,
  action_code          VARCHAR(64) NOT NULL,
  action_reason        VARCHAR(500) NULL,
  operator_type_code   VARCHAR(32) NOT NULL,
  operator_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  operated_at          DATETIME(3) NOT NULL,
  ext_json             JSON NULL,
  created_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted           TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at           DATETIME(3) NULL,
  KEY idx_order_flow_order_time (order_id, operated_at),
  KEY idx_order_flow_to_status (to_status_code),
  KEY idx_order_flow_operator (operator_type_code, operator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单状态流转';

CREATE TABLE pm_backpack_asset (
  id                     BIGINT UNSIGNED PRIMARY KEY,
  tenant_id              BIGINT UNSIGNED NOT NULL DEFAULT 0,
  asset_no               VARCHAR(32) NOT NULL,
  user_id                BIGINT UNSIGNED NOT NULL,
  asset_type_code        VARCHAR(32) NOT NULL,
  asset_name             VARCHAR(256) NOT NULL,
  asset_sub_type_code    VARCHAR(32) NULL,
  source_type_code       VARCHAR(32) NOT NULL,
  source_no              VARCHAR(64) NULL,
  source_order_id        BIGINT UNSIGNED NULL,
  source_order_no        VARCHAR(32) NULL,
  ref_type_code          VARCHAR(32) NULL,
  ref_id                 BIGINT UNSIGNED NULL,
  star_level             INT NULL,
  quantity               INT NOT NULL DEFAULT 1,
  used_quantity          INT NOT NULL DEFAULT 0,
  status_code            VARCHAR(32) NOT NULL DEFAULT 'UNUSED',
  obtain_at              DATETIME(3) NOT NULL,
  valid_start_at         DATETIME(3) NULL,
  valid_end_at           DATETIME(3) NULL,
  activated_at           DATETIME(3) NULL,
  expired_at             DATETIME(3) NULL,
  ext_json               JSON NULL,
  remark                 VARCHAR(500) NULL,
  created_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted             TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at             DATETIME(3) NULL,
  UNIQUE KEY uk_asset_no (tenant_id, asset_no),
  KEY idx_asset_user_status (user_id, status_code),
  KEY idx_asset_user_time (user_id, obtain_at),
  KEY idx_asset_ref (ref_type_code, ref_id),
  KEY idx_asset_valid_end (valid_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='背包资产';

CREATE TABLE pm_backpack_asset_flow (
  id                   BIGINT UNSIGNED PRIMARY KEY,
  tenant_id            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  asset_id             BIGINT UNSIGNED NOT NULL,
  asset_no             VARCHAR(32) NOT NULL,
  user_id              BIGINT UNSIGNED NOT NULL,
  action_code          VARCHAR(64) NOT NULL,
  before_status_code   VARCHAR(32) NULL,
  after_status_code    VARCHAR(32) NOT NULL,
  change_quantity      INT NOT NULL DEFAULT 0,
  action_reason        VARCHAR(500) NULL,
  operator_type_code   VARCHAR(32) NOT NULL DEFAULT 'SYSTEM',
  operator_id          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  occurred_at          DATETIME(3) NOT NULL,
  ext_json             JSON NULL,
  created_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at           DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted           TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at           DATETIME(3) NULL,
  KEY idx_asset_flow_asset_time (asset_id, occurred_at),
  KEY idx_asset_flow_user_time (user_id, occurred_at),
  KEY idx_asset_flow_action (action_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='背包资产流水';

CREATE TABLE pm_idempotent_request (
  id                    BIGINT UNSIGNED PRIMARY KEY,
  tenant_id             BIGINT UNSIGNED NOT NULL DEFAULT 0,
  idempotent_no         VARCHAR(64) NOT NULL,
  scene_code            VARCHAR(64) NOT NULL,
  user_id               BIGINT UNSIGNED NULL,
  request_hash          VARCHAR(128) NULL,
  request_body          JSON NULL,
  response_body         JSON NULL,
  process_status_code   VARCHAR(32) NOT NULL,
  expired_at            DATETIME(3) NULL,
  ext_json              JSON NULL,
  created_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted            TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at            DATETIME(3) NULL,
  UNIQUE KEY uk_idempotent_scene_no (tenant_id, scene_code, idempotent_no),
  KEY idx_idempotent_user (user_id),
  KEY idx_idempotent_expired (expired_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='幂等请求';

SET FOREIGN_KEY_CHECKS = 1;